### ISSUE TITLE
for photos, use `png` and compress them instead of `svg`

### ISSUE THREAD

**Issue by mingyokim** [nwplus/nwhacks2019#103]
`olivia.svg` for e.g. is > 11MB (yikes) so use `png` and compress

promising suspect for #102

**Comment by bobheadxi** [comment]
just tired this lol https://github.com/nwhacks/nwhacks2019/commit/1716ccfcd63c2275dec61f57b614722186ffdbcb

still broken :(

**Comment by mingyokim** [comment]
How big are the png files? And maybe try deleting the svg?
