### ISSUE TITLE
Footer social media buttons not clickable

### ISSUE THREAD

**Issue by lynnzhang7** [nwplus/nwhacks2019#132]

**Comment by StanfordLin** [comment]
Tried to set z-indices for the footer-content and the scenery but still not working mhm...

**Comment by chamkank** [comment]
I think giving the scenery `z-index: -1` and `position: relative` should work

**Comment by StanfordLin** [comment]
Just setting z-index to -1 worked
https://github.com/nwplus/nwhacks2019/pull/151
