### ISSUE TITLE
Update homepage for launch of applications

### ISSUE THREAD

**Issue by chamkank** [nwplus/nwhacks2019#148]
Add the three buttons to apply for hacker / mentor / volunteer

**Comment by mingyokim** [comment]
@chamkank do we need all the buttons by november 1st? or can we just have hacker for now?

also mentor application is not on nwhacks.io right?

**Comment by chamkank** [comment]
Mentor form is just a google form, I'll ask about the volunteer form

**Comment by chamkank** [comment]
https://docs.google.com/forms/d/1HQDZ2YWv8NCkSznOf-Bp6b14gRENiqoSCWYQ8_rYFLM/edit?usp=drivesdk
