### ISSUE TITLE
Target 1080p for standard homepage layout, fix padding

### ISSUE THREAD

**Issue by bobheadxi** [nwplus/nwhacks2019#76]

**Comment by bobheadxi** [comment]
From #92 (@sherryyx ):

> I know there was a bug logged previously about the text and the illustrations not being side by side on macbook pros. Now there's another bug where when the illustration appears below the text, there's a margin-right on the text that's making it horizontally off-centered.

![image](https://user-images.githubusercontent.com/29152180/45009345-84b58080-afbc-11e8-83a2-52cb73582b80.png)

**Comment by chamkank** [comment]
I can take this on once FAQ and footer are merged into master so we can fix it all at once

**Comment by chamkank** [comment]
Also adding to this issue:
- Typo fix (600 -> 650)
- Consistent padding between sections
